export const releaseTypes = [
	{ id: '1standard-album', label: 'Standard Album', value: 'Standard Album' },
	{ id: '2extended-play', label: 'EP', value: 'EP' },
	{ id: '3compilation', label: 'Compilation', value: 'Compilation' },
	{ id: '4single', label: 'Single', value: 'Single' },
	{ id: '5mixtape', label: 'Mixtape', value: 'Mixtape' },
	{ id: '6dj-mix', label: 'DJ Mix', value: 'Dj Mix' },
	{ id: '7acoustic-mix', label: 'Acoustic Mix', value: 'Acoustic Mix' },
	{ id: '8bootleg', label: 'Bootleg', value: 'Bootleg' },
	{ id: '9live-album', label: 'Live Album', value: 'Live Album' },
	{ id: '10soundtrack', label: 'Soundtrack', value: 'Soundtrack' },
	{ id: '11promo', label: 'Promo', value: 'Promo' },
	{
		id: '12cast-recordings',
		label: 'Cast Recordings',
		value: 'Cast Recordings',
	},
	{ id: '13charity-album', label: 'Charity Album', value: 'Charity Album' },
	{ id: '14concept-album', label: 'Concept Album', value: 'Concept Album' },
	{ id: '15cover-album', label: 'Cover Album', value: 'Cover Album' },
	{ id: '16demo-album', label: 'Demo Album', value: 'Demo Album' },
	{ id: '17exploito', label: 'Exploito', value: 'Exploito' },
	{ id: '18remix', label: 'Remix', value: 'Remix' },
	{ id: '19split', label: 'Split', value: 'Split' },
	{ id: '20sampler', label: 'Sampler', value: 'Sampler' },
];
